server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React Frontend
    location / {
        try_files $uri /index.html;
    }

    # Node.js Backend API
    location /api/ {
        proxy_pass http://127.0.0.1:3000/;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;

        proxy_cache_bypass $http_upgrade;
    }
}